### ISSUE TITLE
RuntimeException Errors

### ISSUE THREAD

**Issue by johnathon-b** [duanemck/iis-bluegreen-powershell#2]
When the script gets to stage 3, I begin to receive errors: 

`Method invocation failed because [System.Reflection.RuntimeAssembly] does not contain a method named 'GetCollection'.
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : iis04`

Digging a  bit deeper to see why the Web Administrator module isn't loading correctly. Is there any dependency that I may be missing on the host boxes.

**Comment by duanemck** [comment]
I see GetCollection is called in 2 places:
* Get-ServerFarm
* Get-Server

Can you see which one is failing.

Its possibly a Powershell version issue. What version do you have installed?

**Comment by johnathon-b** [comment]
PSVersion: 5.1.14393.2515

I'm starting to think its the way that the Object is handled between functions. I've install the module on the box and can successfully run Get-ServerFarm and have no issues. As soon as I run Get-Server and it tries to do the GetCollection method on the object $webFarm it errors. 

![image](https://user-images.githubusercontent.com/18176012/46480989-f77e6b00-c7b7-11e8-891c-0fc958698668.png)

**Comment by johnathon-b** [comment]
Turns out I was getting runtime errors because the nodes became inactive. Hitting the nodes with a warm up allows the functions to work.

**Comment by duanemck** [comment]
OK cool good to know. Sorry about the radio silence from my side, been a bit hectic at work.
